### ISSUE TITLE
Cannot autostart the plugin

### ISSUE THREAD

**Issue by glow12121** [manu-mannattil/vim-longlines#4]
I use the lines below to get the plugin autostart. But with these settings it works in a funny way: skipping some displayed soft-wrapped lines, the cursor still jumps to others.  Whereas when I simply type `:LongLines`, everything works just fine.

So my question is: what is the optimal way to get the plugin autostart? I need it for all my buffers because  I only work with markdown and plain-texts.

```
Plug 'manu-mannattil/vim-longlines'
au VimEnter * LongLines
autocmd FileType * LongLines
```

**Comment by manu-mannattil** [comment]
The command `:LongLines` *toggles* the longline mode.  So, with the autocommands you've set up, it would get executed twice -- when VimEnter is triggered and when FileType is triggered.  Could you try using just `autocmd FileType * LongLines`?

**Comment by glow12121** [comment]
Thanks for the feedback. With `autocmd FileType * LongLines` in the config file, things work in the first opened buffer in the current tab, but do not work in other tabs and buffers.

**Comment by manu-mannattil** [comment]
How about using `BufEnter * LongLines`?  FileType events only get triggered after the filetype has been set, but presumably you want to enter the longline mode as soon as you start Vim.

**Comment by glow12121** [comment]
I changed the line to `au BufEnter * LongLines` but, no, it doesn't work.

The current related part of the config:

```
" Plugin to help navigate through long soft-wrapped lines
Plug 'manu-mannattil/vim-longlines'
" au VimEnter * LongLines
" autocmd FileType * LongLines
au BufEnter * LongLines
```

**Comment by manu-mannattil** [comment]
I now see that BufEnter alone will not work as BufEnter gets triggered each time a buffer is entered in a window, and we need to call LongLines exactly once for each buffer.  Could you try the following?

```vim
autocmd BufEnter *
      \ if !exists('b:longlines_called') |
      \   let b:longlines_called = 1     |
      \   LongLines                      |
      \ endif
```

**Comment by glow12121** [comment]
Will try this. Is it impossible to enable the option at Neovim startup once and for all?

**Comment by manu-mannattil** [comment]
> Is it impossible to enable the option at Neovim startup once and for all?

I've updated the plugin. Now you if you include `let g:longlines_always_on = 1` in your `~/.vimrc`, the longline mode is always enabled.  See if this works for you.

**Comment by manu-mannattil** [comment]
> Is it impossible to enable the option at Neovim startup once and for all?

If you really require this, I could create an option `g:longlines_always_enable`, which would do this.  Alternatively, you could merge useful bits of the plugin (see the mapping commands in `longlines.vim`) with your `~/.vimrc` and make them global (i.e., not `<buffer>` maps).

**Comment by glow12121** [comment]
> If you really require this, I could create an option `g:longlines_always_enable`

That would be super-neat of you.

**Comment by manu-mannattil** [comment]
I've pushed a commit that adds an option that will always enable the plugin.  Set it by adding `let g:longlines_always_enable = 1` in your `~/.vimrc`.  Let me know if this is working for you.

**Comment by glow12121** [comment]
Dear @manu-mannattil , it's magic, everything works now in all buffers and tabs. Thank you very much. It's amazing I can talk to a developer of the software I use directly.
